### PR TITLE
Ed25519 Algorithm Support (fixed)

### PR DESCRIPTION
**Pull request by thelunararmy**
Ready for review and merging.

### CODE REVIEW

**Comment by EternalDeiwos** [comment]
Given that we're going a little off-script with this I get that some usage has needed to be guessed.

I think it might be a good idea to structure the usage of EDDSA a little more like ECDSA w.r.t. the `namedCurve` property, even if we're only supporting `ed25519` for now.

Also, on that note: we should specify in the README that we _additionally_ support `K256 (secp256k1)` in ECDSA and _only_ `ed25519` in EDDSA.

**Comment by thelunararmy** [comment]
Implemented most of what you said, the thing left being the `CurrentlyNotSupported` error since, realistically users shouldnt try `ed448` since the new readme specifically only says what is and what isn't supported. See 064f0817b8cf273b1836915a0f8277743822fae7

**Comment by EternalDeiwos** [comment]
Thanks for taking care of that.

Your table that you added to the README looks like we only support `secp256k1` for ECDSA when we also support the NIST curves `P-256/384/512`.

**Comment by thelunararmy** [comment]
Derp, completely forgot. Partially since you added the support for all those. Added to README.

**Comment by EternalDeiwos** [comment]
Looks fantastic. Thank you sir 😁 .

**Pull request merged**
