### PR TITLE
fix(AES-GCM): check for byteLength instead of length

### LINKED ISSUE #58: AES-GCM encrypt throws when passing an ArrayBuffer as data
Seems like the `length` property is being read from the `data`, but that property only exists on typed arrays.

https://github.com/anvilresearch/webcrypto/blob/07129425f5d46f8e65f9f8c9732ad31abdc21537/src/algorithms/AES-GCM.js#L63

https://github.com/anvilresearch/webcrypto/blob/07129425f5d46f8e65f9f8c9732ad31abdc21537/src/algorithms/AES-GCM.js#L68-L71

I think that the proper approach is to read the `byteLength`

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #58

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Great catch, thanks!

**Comment by EternalDeiwos** [comment]
Great catch indeed. Thanks for the PR. You can add yourself to the README as a contributor if you want; otherwise we'll just go ahead and merge this.

**Comment by LinusU** [comment]
I'd be happy to!

done ✔️

**Comment by EternalDeiwos** [comment]
Thanks

**Pull request merged**
